#!/usr/bin/env python3

import requests
import json
import sys

client_id = "cyA5UbJFwCwSozwN7F7OTJEoSpf5"
client_secret = "6a52bea9-a328-49fc-a3ef-69c3095d6b6b",

headers = {
    "content-type": "application/x-www-form-urlencoded",
}

data = {
    "client_secret": client_secret,
    "client_id": client_id,
    "grant_type": "client_credentials",
    "scope": "read:vat",
}

resp = requests.post(
    "https://test-api.service.hmrc.gov.uk/oauth/token", headers=headers,
    data=data
)

if resp.status_code != 200:
    print(resp.text)
    sys.exit(1)

token = resp.json()["access_token"]

headers = {
    "Authorization": "Bearer " + token,
    "Content-Type": "application/json",
    "Accept": "application/vnd.hmrc.1.0+json",
}

data = {
    "serviceNames": [
        "mtd-vat",
    ],
}

url = "https://test-api.service.hmrc.gov.uk/create-test-user/organisations"

resp = requests.post(url, data=json.dumps(data), headers=headers)
if resp.status_code != 201:
    print(resp.text)
    sys.exit(1)

#print(json.dumps(resp.json(), indent=4))

user = resp.json()

def split(x):
    return " ".join([x[i:i+3] for i in range(0, len(x), 3)])

print("User:      ", split(user["userId"]))
print("Password:  ", split(user["password"]))
print("VRN:       ", split(user["vrn"]))

print()

print("Note: space separation for readable, do not include spaces in value.")
