#!/usr/bin/env python3

import sys
import logging

logging.basicConfig(level=logging.DEBUG)

logging.getLogger("cachecontrol.controller").setLevel(logging.ERROR)
logging.getLogger("google.auth.transport.requests").setLevel(logging.ERROR)
logging.getLogger("urllib3.connectionpool").setLevel(logging.ERROR)

from accountsmachine.api import Api

if len(sys.argv) != 2:
    print("Usage:\n\tengine <config>")
    sys.exit(1)

api = Api(sys.argv[1])

api.run()

